services:
  - type: web
    name: pfc-backend
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_EXPIRE_MINUTES
        value: "60"
      - key: JWT_REFRESH_EXPIRE_DAYS
        value: "7"
      - key: ALGORITHM
        value: "HS256"
      - key: CORS_ORIGINS
        value: '["http://localhost:5173","https://school-management-pfe.netlify.app"]'
      - key: API_V1_PREFIX
        value: "/api"
      - key: ENVIRONMENT
        value: "production"

